
from html2image import Html2Image
from pathlib import Path
import tempfile
import os
import shutil

class HtmlImageEngine:
    def __init__(self):
        # We initialize Html2Image once if possible, but for thread-safety it might be better per-request or properly pooled
        pass

    def generate_image(self, html: str, css: str, width: int, height: int, output_path: Path):
        """
        Renders HTML+CSS to an image.
        """
        
        # Create temp dir
        temp_dir = tempfile.mkdtemp()
        
        try:
            filename = output_path.name
            
            # Additional flags for running in docker/container environments
            flags = [
                '--no-sandbox', 
                '--disable-gpu', 
                '--hide-scrollbars',
                '--disable-web-security' # Sometimes helpful for local assets
            ]
            
            # On some systems, we need to point to chromium executable explicitly if not found in PATH
            browser = None
            if os.environ.get("CHROME_BIN"):
                browser = os.environ.get("CHROME_BIN")
            
            # Initialize Html2Image
            # output_path here means "directory where to save the files"
            # We want to save to our temp_dir first
            hti = Html2Image(
                output_path=temp_dir,
                custom_flags=flags, 
                browser=browser
            )

            # We create a full HTML string with HEAD, BODY, and Style imports
            # This is safer than relying on html2image's parsing of fragments
            full_html = f"""
<!DOCTYPE html>
<html>
<head>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;800&display=swap" rel="stylesheet">
    <style>
        body, html {{
            width: {width}px;
            height: {height}px;
            margin: 0;
            padding: 0;
            overflow: hidden;
            background: transparent;
        }}
        /* User CSS injected here */
        {css}
    </style>
</head>
<body>
    {html}
</body>
</html>
"""
            
            # Render
            # We save as 'page.png' or similar because filename might have path issues if passed to save_as?
            # Actually save_as accepts filename only usually.
            temp_filename = "execution.png"
            
            # Taking screenshot
            hti.screenshot(
                html_str=full_html,
                save_as=temp_filename,
                size=(width, height)
            )
            
            # Locate result
            result_path = Path(temp_dir) / temp_filename
            if result_path.exists():
                # Move to final destination (which is a Path object provided by caller)
                # Ensure parent exists? Caller likely provided valid path in existing temp dir.
                shutil.move(str(result_path), str(output_path))
            else:
                 # Last ditch check if it saved with unexpected name
                 possible = list(Path(temp_dir).glob("*.png"))
                 if possible:
                     shutil.move(str(possible[0]), str(output_path))
                 else:
                     raise RuntimeError("Image file not generated by html2image.")
                     
        except Exception as e:
            # Re-raise with context
            raise RuntimeError(f"Html2Image failed: {e}")
        finally:
            if os.path.exists(temp_dir):
                shutil.rmtree(temp_dir)

# Singleton instance
engine_instance = HtmlImageEngine()

def generate_image_from_html(html: str, css: str, width: int, height: int, output_path: Path):
    engine_instance.generate_image(html, css, width, height, output_path)
