from html2image import Html2Image
from pathlib import Path
import tempfile
import os
import shutil

class HtmlImageEngine:
    def generate_image(self, html: str, css: str, width: int, height: int, output_path: Path):
        temp_dir = tempfile.mkdtemp()

        try:
            # Flags recomendadas para container
            flags = [
                "--no-sandbox",
                "--disable-dev-shm-usage",
                "--disable-gpu",
                "--hide-scrollbars",
                "--headless=new",
            ]

            # 1) Preferir variável de ambiente (determinístico)
            browser_executable = os.environ.get("CHROME_BIN")

            # 2) Fallback para paths comuns no Linux/container
            if not browser_executable:
                for p in ["/usr/bin/chromium", "/usr/bin/chromium-browser", "/usr/bin/google-chrome", "/opt/google/chrome/chrome"]:
                    if os.path.exists(p):
                        browser_executable = p
                        break

            # 3) Fallback por PATH (casos nixpacks etc.)
            if not browser_executable:
                for cmd in ["chromium", "chromium-browser", "google-chrome", "google-chrome-stable", "chrome"]:
                    found = shutil.which(cmd)
                    if found:
                        browser_executable = found
                        break

            # Inicializa Html2Image
            hti_kwargs = dict(output_path=temp_dir, custom_flags=flags)
            if browser_executable:
                hti_kwargs["browser_executable"] = browser_executable

            hti = Html2Image(**hti_kwargs)

            full_html = f"""<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8" />
  <link rel="preconnect" href="https://fonts.googleapis.com">
  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
  <link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;800&display=swap" rel="stylesheet">
  <style>
    html, body {{
      width: {width}px;
      height: {height}px;
      margin: 0;
      padding: 0;
      overflow: hidden;
      background: transparent;
    }}
    {css}
  </style>
</head>
<body>
  {html}
</body>
</html>
"""

            temp_filename = "execution.png"

            hti.screenshot(
                html_str=full_html,
                save_as=temp_filename,
                size=(width, height),
            )

            result_path = Path(temp_dir) / temp_filename
            if not result_path.exists():
                pngs = list(Path(temp_dir).glob("*.png"))
                if pngs:
                    result_path = pngs[0]
                else:
                    raise RuntimeError("Image file not generated by html2image.")

            output_path.parent.mkdir(parents=True, exist_ok=True)
            shutil.move(str(result_path), str(output_path))

        except Exception as e:
            raise RuntimeError(f"Html2Image failed: {e}")
        finally:
            shutil.rmtree(temp_dir, ignore_errors=True)

engine_instance = HtmlImageEngine()

def generate_image_from_html(html: str, css: str, width: int, height: int, output_path: Path):
    engine_instance.generate_image(html, css, width, height, output_path)